apiVersion: apps/v1
kind: Deployment
Namespace: lucas-space
metadata:     
  name: nginx-deployment  
  labels:
     app: nginx  
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: shashwot/nginx-more:latest
        ports:
        - containerPort: 80
